[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "torch-split"
version = "0.1.0"
description = "PyTorch model analysis and splitting tool"
requires-python = ">=3.10, <3.14"

dependencies = [
    "torch>=2.8.0",
    "frozendict>=2.4.6",
    "graphviz>=0.21.0",
    "opentelemetry-api>=1.37.0",
    "opentelemetry-sdk>=1.37.0",
    "opentelemetry-exporter-otlp-proto-http>=1.37.0",
    "pydantic>=2.12.0",
    "numpy>=2.2.6",
    "msgpack>=1.1.2",
    "rich>=14.2.0",
    "gurobipy (>=13.0.0,<14.0.0)",
]

[project.optional-dependencies]
typing = ["types-frozendict"]

[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "pillow (>=12.0.0,<13.0.0)",
    "transformers (>=4.57.1,<5.0.0)",
    "isort (>=7.0.0,<8.0.0)",
    "black (>=25.11.0,<26.0.0)",
    "ruff (>=0.14.4,<0.15.0)"
]
